name: Release - Publish Docker Image

on:
  workflow_dispatch:
    inputs:
      # image_type:
      #   description: Type of the image to be published
      #   required: true
      #   default: rc
      #   type: choice
      #   options:
      #     - rc
      #     - release

      binary:
        description: Binary to be published
        required: true
        default: all
        type: choice
        options:
          - all
          - polkadot
          # - polkadot-omni-node
          - polkadot-parachain
          # - chain-spec-builder

      registry:
        description: Container registry
        required: true
        type: string
        default: docker.io

      # The owner is often the same as the Docker Hub username but does ont have to be.
      # In our case, it is not.
      owner:
        description: Owner of the container image repo
        required: true
        type: string
        default: parity

      version:
        description: Version of the polkadot node release in format v1.XX.X-weeklyW#
        default: v1.19.0-weeklyW1
        required: true

      weekly_release_tag:
        description: Tag matching the actual weekly release version in the format polkadot-weeklyW#
        required: true
      build_run_id:
        description: Run ID of the current release workflow run to be used to download the artifacts
        required: true
        type: string

  workflow_call:
    inputs:
      binary:
        description: Binary to be published
        required: true
        default: '[ "polkadot", "polkadot-parachain" ]'
        type: string

      registry:
        description: Container registry
        required: true
        type: string
        default: docker.io

      # The owner is often the same as the Docker Hub username but does ont have to be.
      # In our case, it is not.
      owner:
        description: Owner of the container image repo
        required: true
        type: string
        default: parity

      version:
        description: Version of the polkadot node release in format v1.XX.X-weeklyW#
        default: v1.19.0-weeklyW1
        required: true
        type: string

      weekly_release_tag:
        description: Tag matching the actual weekly release version in the format polkadot-weeklyW#
        required: true
        type: string
      build_run_id:
        description: Run ID of the current release workflow run to be used to download the artifacts
        required: true
        type: string

    secrets:
      RELEASE_AUTOMATION_APP_PRIVATE_KEY:
        required: true

permissions:
  contents: write
  id-token: write
  actions: read

env:
  ENGINE: docker
  REGISTRY: ${{ inputs.registry }}
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  DOCKER_OWNER: ${{ inputs.owner || github.repository_owner }}
  REPO: ${{ github.repository }}
  BINARY: ${{ inputs.binary }}
  # IMAGE_TYPE: ${{ inputs.image_type }}

jobs:
  validate-inputs:
    runs-on: parity-default
    outputs:
      version: ${{ steps.validate_inputs.outputs.VERSION }}
      weekly_release_tag: ${{ steps.validate_inputs.outputs.weekly_release_tag }}

    steps:
      - name: Checkout sources
        uses: actions/checkout@d632683dd7b4114ad314bca15554477dd762a938 # v4.2.0

      - name: Validate inputs
        id: validate_inputs
        run: |
          . ./.github/scripts/common/lib.sh

          VERSION=$(filter_version_from_input "${{ inputs.version }}")
          echo "VERSION=${VERSION}" >> $GITHUB_OUTPUT

          RELEASE_TAG=$(validate_weekly_release_tag ${{ inputs.weekly_release_tag }})
          echo "weekly_release_tag=${RELEASE_TAG}" >> $GITHUB_OUTPUT

  set-up-binaries:
    runs-on: parity-default
    needs: [ validate-inputs ]
    outputs:
      binaries: ${{ steps.set_up_binaries.outputs.binaries }}
    steps:
      - name: Checkout sources
        uses: actions/checkout@d632683dd7b4114ad314bca15554477dd762a938 # v4.2.0

      - name: Set up binaries matrix
        id: set_up_binaries
        run: |
          . ./.github/scripts/common/lib.sh

          if [ "$BINARY" == "all" ]; then
              MATRIX='["polkadot", "polkadot-parachain"]'
              echo $MATRIX
              echo "binaries=$MATRIX" >> $GITHUB_OUTPUT
            else
              MATRIX='["${{env.BINARY}}"]'
              echo "binaries=$MATRIX" >> $GITHUB_OUTPUT
            fi

  build-container:
    runs-on: parity-default
    needs: [ validate-inputs, set-up-binaries ]
    environment: release
    strategy:
      matrix:
        binary: ${{ fromJson(needs.set-up-binaries.outputs.binaries) }}
    steps:
      - name: Checkout sources
        uses: actions/checkout@d632683dd7b4114ad314bca15554477dd762a938 # v4.2.0
        with:
          repository: paritytech/polkadot-sdk
          ref: ${{ needs.validate-inputs.outputs.weekly_release_tag }}
          fetch-depth: 0

      - name: Generate content write token for the release automation
        id: generate_write_token
        uses: actions/create-github-app-token@v2
        with:
            app-id: ${{ vars.RELEASE_AUTOMATION_APP_ID }}
            private-key: ${{ secrets.RELEASE_AUTOMATION_APP_PRIVATE_KEY }}
            owner: paritytech

      - name: Download artifacts
        env:
          GITHUB_TOKEN: ${{ steps.generate_write_token.outputs.token }}
          RUN_ID: ${{ inputs.build_run_id }}
        run: |
          (type -p wget >/dev/null || (sudo apt update && sudo apt install wget -y)) \
            && sudo mkdir -p -m 755 /etc/apt/keyrings \
            && out=$(mktemp) && wget -nv -O$out https://cli.github.com/packages/githubcli-archive-keyring.gpg \
            && cat $out | sudo tee /etc/apt/keyrings/githubcli-archive-keyring.gpg > /dev/null \
            && sudo chmod go+r /etc/apt/keyrings/githubcli-archive-keyring.gpg \
            && sudo mkdir -p -m 755 /etc/apt/sources.list.d \
            && echo "deb [arch=$(dpkg --print-architecture) signed-by=/etc/apt/keyrings/githubcli-archive-keyring.gpg] https://cli.github.com/packages stable main" | sudo tee /etc/apt/sources.list.d/github-cli.list > /dev/null \
            && sudo apt update \
            && sudo apt install gh -y

          mkdir -p ${{ github.workspace}}/release-artifacts/
          gh run download ${{ env.RUN_ID }} --repo paritytech/release-automation --dir ${{ github.workspace}}/release-artifacts -p "polkadot*"
          # move all the downloadedfiles to the root directory
          find ${{ github.workspace}}/release-artifacts -mindepth 2 -type f -print0 | xargs -0 -I{} mv {} ${{ github.workspace}}/release-artifacts/
          # delete all the empty directories
          find ${{ github.workspace}}/release-artifacts -mindepth 1 -type d -empty -delete

      - name: Check sha256 ${{ matrix.binary }}
        # if: ${{ inputs.binary == 'polkadot-parachain' || inputs.binary == 'polkadot' }}
        working-directory: release-artifacts
        run: |
          . ../.github/scripts/common/lib.sh

          if [[ ${{ matrix.binary }} == 'polkadot' ]]; then
            bins=(polkadot polkadot-prepare-worker polkadot-execute-worker)
            for bin in "${bins[@]}"; do
              echo "Checking binary $bin"
              check_sha256 $bin && echo "OK" || echo "ERR"
            done
          else
            echo "Checking binary ${{ matrix.binary }}"
            check_sha256 ${{ matrix.binary }} && echo "OK" || echo "ERR"
          fi

      # - name: Check GPG ${{ env.BINARY }}
      #   # if: ${{ inputs.binary == 'polkadot-parachain' || inputs.binary == 'polkadot' }}
      #   working-directory: release-artifacts
      #   run: |
      #     . ../.github/scripts/common/lib.sh
      #     import_gpg_keys
      #     check_gpg $BINARY

      - name: Fetch weekly rc commit and tag
        working-directory: release-artifacts
        # if: ${{ env.IMAGE_TYPE == 'rc' }}
        id: fetch_rc_refs
        shell: bash
        run: |
          . ../.github/scripts/common/lib.sh
          weekly_tag="${{ needs.validate-inputs.outputs.weekly_release_tag }}"

          commit=$(git rev-parse --short HEAD) && \
          echo "commit=${commit}" >> $GITHUB_OUTPUT

          rc_suffix=$(echo $weekly_tag | sed -n 's/.*\(-rc[0-9]\+\)/\1/p')
          echo "release=$(echo ${{ needs.validate-inputs.outputs.version }})$rc_suffix" >> $GITHUB_OUTPUT

          docker_tag="${weekly_tag#polkadot-}"
          echo "tag=$docker_tag" >> $GITHUB_OUTPUT

      # - name: Fetch release tags
      #   working-directory: release-artifacts
      #   if: ${{ env.IMAGE_TYPE == 'release'}}
      #   id: fetch_release_refs
      #   shell: bash
      #   run: |
      #     . ../.github/scripts/common/lib.sh

      #     echo "tag=latest" >> $GITHUB_OUTPUT
      #     echo "release=$(echo ${{ needs.validate-inputs.outputs.version }})" >> $GITHUB_OUTPUT
      #     echo "stable=$(prepare_docker_stable_tag ${{ needs.validate-inputs.outputs.stable_tag }})" >> $GITHUB_OUTPUT

      - name: Build Injected Container image for polkadot rc
        if: ${{ matrix.binary == 'polkadot' }}
        env:
          ARTIFACTS_FOLDER: release-artifacts
          IMAGE_NAME: polkadot
          OWNER: ${{ env.DOCKER_OWNER }}
          TAGS: ${{ join(steps.fetch_rc_refs.outputs.*, ',') }}
          BINARY: ${{ matrix.binary }}
        run: |
          ls -al
          echo "Building container for polkadot"
          ./docker/scripts/polkadot/build-injected.sh $ARTIFACTS_FOLDER

      - name: Build Injected Container image for polkadot-omni-node/chain-spec-builder
      #if: ${{ env.BINARY == 'polkadot-omni-node' || env.BINARY == 'chain-spec-builder' }}
        if: ${{ matrix.binary == 'polkadot-omni-node' }}
        env:
          ARTIFACTS_FOLDER: release-artifacts
          IMAGE_NAME: ${{ matrix.binary }}
          OWNER: ${{ env.DOCKER_OWNER }}
          TAGS: ${{ join(steps.fetch_rc_refs.outputs.*, ',') }}
          BINARY: ${{ matrix.binary }}
        run: |
          ls -al
          echo "Building container for $${{ matrix.binary }}"
          ./docker/scripts/build-injected.sh

      - name: Build Injected Container image for polkadot-parachain
        if: ${{ matrix.binary == 'polkadot-parachain' }}
        env:
          ARTIFACTS_FOLDER: release-artifacts
          IMAGE_NAME: polkadot-parachain
          OWNER: ${{ env.DOCKER_OWNER }}
          DOCKERFILE: docker/dockerfiles/polkadot-parachain/polkadot-parachain_injected.Dockerfile
          TAGS: ${{ join(steps.fetch_rc_refs.outputs.*, ',') }}
          BINARY: ${{ matrix.binary }}
        run: |
          ls -al
          ls -al $ARTIFACTS_FOLDER
          mkdir -p $ARTIFACTS_FOLDER/specs
          cp cumulus/parachains/chain-specs/*.json $ARTIFACTS_FOLDER/specs

          echo "Building container for polkadot-parachain"
          ./docker/scripts/build-injected.sh

      - name: Login to Dockerhub to publish polkadot
        if: ${{ matrix.binary == 'polkadot' }}
        uses: docker/login-action@9780b0c442fbb1117ed29e0efdff1e18412f7567 # v3.3.0
        with:
          username: ${{ secrets.POLKADOT_DOCKERHUB_USERNAME }}
          password: ${{ secrets.POLKADOT_DOCKERHUB_TOKEN }}

      - name: Login to Dockerhub to publish polkadot-omni-node/polkadot-parachain/chain-spec-builder
        # if: ${{ matrix.binary  == 'polkadot-omni-node' || matrix.binary == 'polkadot-parachain' || matrix.binary == 'chain-spec-builder' }}
        if: ${{ matrix.binary  == 'polkadot-omni-node' || matrix.binary == 'polkadot-parachain' }}
        uses: docker/login-action@9780b0c442fbb1117ed29e0efdff1e18412f7567 # v3.3.0
        with:
          username: ${{ secrets.CUMULUS_DOCKERHUB_USERNAME }}
          password: ${{ secrets.CUMULUS_DOCKERHUB_TOKEN }}

      - name: Push Container image for ${{ matrix.binary }}
        id: docker_push
        run: |
          $ENGINE images | grep ${{ matrix.binary }}
          $ENGINE push --all-tags ${REGISTRY}/${DOCKER_OWNER}/${{ matrix.binary }}

      - name: Check version for the published image for ${{ matrix.binary }}
        env:
          RELEASE_TAG: ${{ steps.fetch_rc_refs.outputs.release }}
        run: |
          echo "Checking tag ${RELEASE_TAG} for image ${REGISTRY}/${DOCKER_OWNER}/${{ matrix.binary }}"
          if [[ ${{ matrix.binary }} == 'chain-spec-builder' ]]; then
            $ENGINE run -i ${REGISTRY}/${DOCKER_OWNER}/${{ matrix.binary }}:${RELEASE_TAG}
          else
            $ENGINE run -i ${REGISTRY}/${DOCKER_OWNER}/${{ matrix.binary }}:${RELEASE_TAG} --version
          fi

  # fetch-latest-debian-package-version: # this job will be triggered for polkadot release build
  #   if: ${{ inputs.binary == 'polkadot' && inputs.image_type == 'release' }}
  #   runs-on: parity-default
  #   outputs:
  #     polkadot_apt_version: ${{ steps.fetch-latest-apt.outputs.polkadot_apt_version }}
  #     polkadot_container_tag: ${{ steps.fetch-latest-apt.outputs.polkadot_container_tag }}
  #   container:
  #     image: paritytech/parity-keyring
  #     options: --user root
  #   steps:
  #     - name: Get version
  #       id: fetch-latest-apt
  #       run: |
  #         apt update
  #         apt show polkadot
  #         version=$(apt show polkadot 2>/dev/null | grep "Version:" | awk '{print $2}')
  #         tag=$(echo $version | sed 's/-.*//')
  #         echo "polkadot_apt_version=v$version" >> $GITHUB_OUTPUT
  #         echo "polkadot_container_tag=v$tag" >> $GITHUB_OUTPUT
  #         echo "You passed ${{ inputs.version }} but this is ignored"
  #         echo "We use the version from the Debian Package: $version"

  # build-polkadot-release-container: # this job will be triggered for polkadot release build
  #   if: ${{ inputs.binary == 'polkadot' && inputs.image_type == 'release' }}
  #   runs-on: parity-default
  #   needs: [ fetch-latest-debian-package-version, validate-inputs ]
  #   environment: release
  #   steps:
  #     - name: Checkout sources
  #       uses: actions/checkout@d632683dd7b4114ad314bca15554477dd762a938 # v4.2.0

  #     - name: Set up Docker Buildx
  #       uses: docker/setup-buildx-action@b5ca514318bd6ebac0fb2aedd5d36ec1b5c232a2 # v3.10.0

  #     - name: Cache Docker layers
  #       uses: actions/cache@d4323d4df104b026a6aa633fdb11d772146be0bf # v4.2.2
  #       with:
  #         path: /tmp/.buildx-cache
  #         key: ${{ runner.os }}-buildx-${{ github.sha }}
  #         restore-keys: |
  #           ${{ runner.os }}-buildx-

  #     - name: Login to Docker Hub
  #       uses: docker/login-action@9780b0c442fbb1117ed29e0efdff1e18412f7567 # v3.3.0
  #       with:
  #         username: ${{ secrets.POLKADOT_DOCKERHUB_USERNAME }}
  #         password: ${{ secrets.POLKADOT_DOCKERHUB_TOKEN }}

  #     - name: Fetch values
  #       id: fetch-data
  #       run: |
  #         . ./.github/scripts/common/lib.sh
  #         date=$(date -u '+%Y-%m-%dT%H:%M:%SZ')
  #         echo "date=$date" >> $GITHUB_OUTPUT
  #         echo "stable=$(prepare_docker_stable_tag ${{ needs.validate-inputs.outputs.stable_tag }})" >> $GITHUB_OUTPUT

  #     - name: Build and push
  #       id:   docker_build
  #       uses: docker/build-push-action@5e99dacf67635c4f273e532b9266ddb609b3025a #  v6.9.0
  #       with:
  #         push: true
  #         file: docker/dockerfiles/polkadot/polkadot_injected_debian.Dockerfile
  #         # TODO: The owner should be used below but buildx does not resolve the VARs
  #         # TODO: It would be good to get rid of this GHA that we don't really need.
  #         tags: |
  #           parity/polkadot:${{ steps.fetch-data.outputs.stable }}
  #           parity/polkadot:latest
  #           parity/polkadot:${{ needs.fetch-latest-debian-package-version.outputs.polkadot_container_tag }}
  #         build-args: |
  #           VCS_REF=${{ github.ref }}
  #           POLKADOT_VERSION=${{ needs.fetch-latest-debian-package-version.outputs.polkadot_apt_version }}
  #           BUILD_DATE=${{ steps.fetch-data.outputs.date }}
  #         cache-from: type=local,src=/tmp/.buildx-cache
  #         cache-to: type=local,dest=/tmp/.buildx-cache
  #     - name: Image digest
  #       run: echo ${{ steps.docker_build.outputs.digest }}
