name: Release - Build runtimes

on:
  workflow_dispatch:
    inputs:
      chain:
        description: The chain to use for a build
        default: all
        required: true
        type: choice
        options:
          - all
          - westend
          - asset-hub-westend
          - bridge-hub-westend
          - collectives-westend
          - coretime-westend
          - glutton-westend
          - people-westend
      runtime_dir:
        description: The runtime dir to be used (⚠️ this parameter is optional and needed only in case of the single runtime build, set it accordingly to the runtime you want to build)
        default: polkadot/runtime/westend
        type: choice
        options:
          - polkadot/runtime/westend
          - cumulus/parachains/runtimes/assets/asset-hub-westend
          - cumulus/parachains/runtimes/bridge-hubs/bridge-hub-westend
          - cumulus/parachains/runtimes/collectives/collectives-westend
          - cumulus/parachains/runtimes/coretime/coretime-westend
          - cumulus/parachains/runtimes/glutton/glutton-westend
          - cumulus/parachains/runtimes/people/people-westend

      weekly_release_tag:
        description: Tag matching the actual release candidate with the format polkadot-weeklyYYYYw#-rcX (e.g. polkadot-weekly2025w1-rc1)
        type: string

  workflow_call:
    inputs:
      chain:
        description: The chain to use for a build
        default: all
        required: true
        type: string
      runtime_dir:
        description: The runtime_dir to be used (⚠️ this parameter is optional and needed only in case of the single runtime build, set it accordingly to the runtime you want to build)
        default: polkadot/runtime/westend
        type: string
      weekly_release_tag:
        description: Tag matching the actual release candidate with the format polkadot-weeklyYYYYw#-rcX (e.g. polkadot-weekly2025w1-rc1)
        type: string

    outputs:
      published_runtimes:
        value: ${{ jobs.build-runtimes.outputs.published_runtimes }}

jobs:
  validate-inputs:
    runs-on: parity-default
    outputs:
        weekly_release_tag: ${{ steps.validate_inputs.outputs.weekly_release_tag }}
    steps:
      - name: Checkout sources
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - name: Validate inputs
        id: validate_inputs
        run: |
          . ./.github/scripts/common/lib.sh

          RELEASE_TAG=$(validate_weekly_release_tag ${{ inputs.weekly_release_tag }})
          echo "weekly_release_tag=${RELEASE_TAG}" >> $GITHUB_OUTPUT

  build-runtimes:
    needs: [validate-inputs]
    uses: "./.github/workflows/release-srtool.yml"
    with:
       excluded_runtimes: "asset-hub-rococo bridge-hub-rococo coretime-rococo people-rococo rococo rococo-parachain substrate-test bp cumulus-test kitchensink minimal-template parachain-template penpal polkadot-test seedling shell frame-try sp solochain-template polkadot-sdk-docs-first pallet-staking-async-parachain pallet-staking-async-rc frame-storage-access-test yet-another-parachain revive-dev"
       build_opts: "--features on-chain-release-build"
       profile: production
       chain: ${{ inputs.chain }}
       runtime_dir: ${{ inputs.runtime_dir }}
       weekly_release_tag: ${{ needs.validate-inputs.outputs.weekly_release_tag }}
    permissions:
      id-token: write
      attestations: write
      contents: read

  # trigger-release-draft:
  #   needs: [build-runtimes, validate-inputs]
  #   runs-on: parity-default
  #   steps:
  #     - name: Generate content write token for the release automation
  #       id: generate_write_token
  #       uses: actions/create-github-app-token@v2
  #       with:
  #           app-id: ${{ vars.POLKADOT_SDK_RELEASE_RW_APP_ID }}
  #           private-key: ${{ secrets.POLKADOT_SDK_RELEASE_RW_APP_KEY }}
  #           owner: paritytech
  #           repositories: polkadot-sdk

  #     - name: Trigger publish_release_draft workflow
  #       env:
  #         GITHUB_TOKEN: ${{ steps.generate_write_token.outputs.token }}
  #       run: |
  #         gh workflow run .github/workflows/release-30_publish_release_draft.yml \
  #           --repo ${{ github.repository }} \
  #           --ref ${{ github.ref }} \
  #           -f weekly_release_tag=${{ needs.validate-inputs.outputs.weekly_release_tag }} \
  #           -f build_run_id=${{ github.run_id }} \
  #           -f runtimes='${{ needs.build-runtimes.outputs.published_runtimes }}'
