name: Release - Combined release flow

on:
  workflow_dispatch:
    inputs:
      weekly_version:
        description: The version of the weekly release in the format weeklyW# that will be used as branch name and rc tag base
        default: weeklyW1
        required: true
        type: string

      node_version:
        description: Version of the polkadot node in the format X.XX.X-weeklyW# (e.g. 1.15.0-weeklyW1).
        default: 1.999.0-weeklyW1
        required: true
        type: string

      is_new_weekly:
        description: ⚠️ Check this box if this is a new weekly release and the weekly release branch needs to be created
        type: boolean

      binary:
        description: Binary to be build for the release
        default: all
        type: choice
        options:
          - all
          - polkadot
          - polkadot-parachain
          # - polkadot-omni-node
          # - frame-omni-bencher
          # - chain-spec-builder
      chain:
        description: The chain to use
        default: all
        required: true
        type: choice
        options:
          - all
          - westend
          - asset-hub-westend
          - bridge-hub-westend
          - collectives-westend
          - coretime-westend
          - glutton-westend
          - people-westend
      runtime_dir:
        description: The runtime dir to be used (⚠️ this parameter is optional and needed only in case of the single runtime build, set it accordingly to the runtime you want to build)
        default: polkadot/runtime/westend
        type: choice
        options:
          - polkadot/runtime/westend
          - cumulus/parachains/runtimes/assets/asset-hub-westend
          - cumulus/parachains/runtimes/bridge-hubs/bridge-hub-westend
          - cumulus/parachains/runtimes/collectives/collectives-westend
          - cumulus/parachains/runtimes/coretime/coretime-westend
          - cumulus/parachains/runtimes/glutton/glutton-westend
          - cumulus/parachains/runtimes/people/people-westend

jobs:
  validate-inputs:
    runs-on: parity-default
    outputs:
      node_version: ${{ steps.validate_inputs.outputs.node_version }}
      weekly_version: ${{ steps.validate_inputs.outputs.weekly_version }}

    steps:
      - name: Checkout sources
        uses: actions/checkout@6d193bf28034eafb982f37bd894289fe649468fc # v4.1.7

      - name: Validate inputs
        id: validate_inputs
        run: |
          . ./.github/scripts/common/lib.sh

          if [ -n "${{ inputs.node_version }}" ]; then
            node_version=$(filter_version_from_input "${{ inputs.node_version }}")
            echo "node_version=${node_version}" >> $GITHUB_OUTPUT
          fi

          weekly_version=$(validate_weekly_release_tag ${{ inputs.weekly_version }})
          echo "weekly_version=${weekly_version}" >> $GITHUB_OUTPUT

  create-or-update-weekly-branch:
    needs: [ validate-inputs ]
    uses: ./.github/workflows/release-10_branchoff-weekly.yml
    with:
      weekly_version: ${{ needs.validate-inputs.outputs.weekly_version }}
      node_version: ${{ needs.validate-inputs.outputs.node_version }}
      is_new_weekly: ${{ inputs.is_new_weekly }}
    secrets:
      PGP_KMS_SIGN_COMMITS_KEY:  ${{ secrets.PGP_KMS_SIGN_COMMITS_KEY }}
      PGP_KMS_HASH:  ${{ secrets.PGP_KMS_HASH }}
      AWS_ACCESS_KEY_ID:  ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_DEFAULT_REGION:  ${{ secrets.AWS_DEFAULT_REGION }}
      RELEASE_AUTOMATION_APP_PRIVATE_KEY: ${{ secrets.RELEASE_AUTOMATION_APP_PRIVATE_KEY }}
      # RELEASENOTES_MATRIX_V2_ACCESS_TOKEN: ${{ secrets.RELEASENOTES_MATRIX_V2_ACCESS_TOKEN }}

  tag-weekly-rc:
    needs: [ validate-inputs, create-or-update-weekly-branch ]
    uses: ./.github/workflows/release-11_rc-automation.yml
    with:
      weekly_version: ${{ needs.validate-inputs.outputs.weekly_version }}
    secrets:
      PGP_KMS_SIGN_COMMITS_KEY:  ${{ secrets.PGP_KMS_SIGN_COMMITS_KEY }}
      PGP_KMS_HASH:  ${{ secrets.PGP_KMS_HASH }}
      AWS_ACCESS_KEY_ID:  ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_DEFAULT_REGION:  ${{ secrets.AWS_DEFAULT_REGION }}
      RELEASE_AUTOMATION_APP_PRIVATE_KEY: ${{ secrets.RELEASE_AUTOMATION_APP_PRIVATE_KEY }}
      # RELEASENOTES_MATRIX_V2_ACCESS_TOKEN: ${{ secrets.RELEASENOTES_MATRIX_V2_ACCESS_TOKEN }}

  build-weekly-rc:
    needs: [ tag-weekly-rc ]
    uses: ./.github/workflows/release-20_build-rc.yml
    with:
      binary: ${{ inputs.binary }}
      weekly_release_tag: ${{ needs.tag-weekly-rc.outputs.rc_tag }}
    permissions:
      id-token: write
      attestations: write
      contents: read

  build-runtimes:
    needs: [ tag-weekly-rc ]
    uses: ./.github/workflows/release-21_build-runtimes.yml
    with:
      chain: ${{ inputs.chain }}
      runtime_dir: ${{ inputs.runtime_dir }}
      weekly_release_tag: ${{ needs.tag-weekly-rc.outputs.rc_tag }}

  build-weekly-rc-docker-images:
    needs: [ tag-weekly-rc, build-weekly-rc ]
    uses: ./.github/workflows/release-50_publish-docker.yml
    with:
      binary: ${{ inputs.binary }}
      weekly_release_tag: ${{ needs.tag-weekly-rc.outputs.rc_tag }}
      registry: docker.io
      owner: parity
      version: ${{ inputs.node_version }}
    secrets:
       RELEASE_AUTOMATION_APP_PRIVATE_KEY: ${{ secrets.RELEASE_AUTOMATION_APP_PRIVATE_KEY }}
permissions:
  contents: write
  id-token: write
  actions: read
