name: Release - Combined release flow

on:
  workflow_dispatch:
    inputs:
      weekly_version:
        description: The version of the weekly release in the format weeklyW# that will be used as branch name and rc tag base
        required: true
        type: string

      node_version:
        description: Version of the polkadot node in the format X.XX.X-weeklyW# (e.g. 1.15.0-weeklyW1).
        required: true
        type: string

      is_new_weekly:
        description: Check this box if this is a new weekly release and the weekly release branch needs to be created
        type: boolean

jobs:
  validate-inputs:
    runs-on: ubuntu-latest
    outputs:
      node_version: ${{ steps.validate_inputs.outputs.node_version }}
      weekly_version: ${{ steps.validate_inputs.outputs.weekly_version }}

    steps:
      - name: Checkout sources
        uses: actions/checkout@6d193bf28034eafb982f37bd894289fe649468fc # v4.1.7

      - name: Validate inputs
        id: validate_inputs
        run: |
          . ./.github/scripts/common/lib.sh

          if [ -n "${{ inputs.node_version }}" ]; then
            node_version=$(filter_version_from_input "${{ inputs.node_version }}")
            echo "node_version=${node_version}" >> $GITHUB_OUTPUT
          fi

          weekly_version=$(validate_weekly_release_tag ${{ inputs.weekly_version }})
          echo "weekly_version=${weekly_version}" >> $GITHUB_OUTPUT

  create-weekly-branch-and-tag:
    needs: [ validate-inputs ]
    uses: ./.github/workflows/release-10_branchoff-weekly.yml
    with:
      weekly_version: ${{ needs.validate-inputs.outputs.weekly_version }}
      node_version: ${{ needs.validate-inputs.outputs.node_version }}
      is_new_weekly: ${{ inputs.is_new_weekly }}
    secrets:
      PGP_KMS_SIGN_COMMITS_KEY:  ${{ secrets.PGP_KMS_SIGN_COMMITS_KEY }}
      PGP_KMS_HASH:  ${{ secrets.PGP_KMS_HASH }}
      AWS_ACCESS_KEY_ID:  ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_DEFAULT_REGION:  ${{ secrets.AWS_DEFAULT_REGION }}
      RELEASE_AUTOMATION_APP_PRIVATE_KEY: ${{ secrets.RELEASE_AUTOMATION_APP_PRIVATE_KEY }}
      # RELEASENOTES_MATRIX_V2_ACCESS_TOKEN: ${{ secrets.RELEASENOTES_MATRIX_V2_ACCESS_TOKEN }}
