# This workflow has combined functionality of branching-off a new weekly release branch and tagging a weekly RC.
name: Release - Branch off weekly branch and tag weekly rc

on:
  workflow_dispatch:
    inputs:
      weekly_version:
        description: The version of the weekly release in the format weeklyW# that will be used as branch name and rc tag base
        required: true
        type: string

      node_version:
        description: Version of the polkadot node in the format X.XX.X-weeklyW# (e.g. 1.15.0-weeklyW1).
        type: string

      is_new_weekly:
        description: Check this box if this is a new weekly release and the weekly release branch needs to be created
        type: boolean

  workflow_call:
    inputs:
      weekly_version:
        description: The version of the weekly release in the format weeklyW# that will be used as branch name and rc tag base
        required: true
        type: string

      node_version:
        description: Version of the polkadot node in the format X.XX.X-weeklyW# (e.g. 1.15.0-weeklyW1).
        type: string

      is_new_weekly:
        description: Check this box if this is a new weekly release and the weekly release branch needs to be created
        type: boolean
    secrets:
      PGP_KMS_SIGN_COMMITS_KEY:
        required: true
      PGP_KMS_HASH:
        required: true
      AWS_ACCESS_KEY_ID:
        required: true
      AWS_SECRET_ACCESS_KEY:
        required: true
      AWS_DEFAULT_REGION:
        required: true
      RELEASE_BACKPORT_AUTOMATION_APP_PRIVATE_KEY:
        required: true
      # RELEASENOTES_MATRIX_V2_ACCESS_TOKEN:
      #   required: true

jobs:
  validate-inputs:
    runs-on: ubuntu-latest
    outputs:
      node_version: ${{ steps.validate_inputs.outputs.node_version }}
      weekly_version: ${{ steps.validate_inputs.outputs.weekly_version }}

    steps:
      - name: Checkout sources
        uses: actions/checkout@6d193bf28034eafb982f37bd894289fe649468fc # v4.1.7

      - name: Validate inputs
        id: validate_inputs
        run: |
          . ./.github/scripts/common/lib.sh

          if [ -n "${{ inputs.node_version }}" ]; then
            node_version=$(filter_version_from_input "${{ inputs.node_version }}")
            echo "node_version=${node_version}" >> $GITHUB_OUTPUT
          fi

          weekly_version=$(validate_weekly_release_tag ${{ inputs.weekly_version }})
          echo "weekly_version=${weekly_version}" >> $GITHUB_OUTPUT

  create-stable-branch:
    needs: [ validate-inputs ]
    runs-on: ubuntu-latest
    environment: release
    env:
      PGP_KMS_KEY: ${{ secrets.PGP_KMS_SIGN_COMMITS_KEY }}
      PGP_KMS_HASH: ${{ secrets.PGP_KMS_HASH }}
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_DEFAULT_REGION: ${{ secrets.AWS_DEFAULT_REGION }}
      WEEKLY_BRANCH_NAME: ${{ needs.validate-inputs.outputs.weekly_version }}

    steps:
      - name: Install pgpkkms
        run: |
          # Install pgpkms that is used to sign commits
          pip install git+https://github.com/paritytech-release/pgpkms.git@e7f806f99e9be5c52f0b4a536b7d4ef9c3e695ed

      - name: Generate content write token for the release automation
        id: generate_write_token
        uses: actions/create-github-app-token@v2
        with:
            app-id: ${{ secrets.RELEASE_BACKPORT_AUTOMATION_APP_ID }}
            private-key: ${{ secrets.RELEASE_BACKPORT_AUTOMATION_APP_PRIVATE_KEY }}
            owner: EgorPopelyaev

      - name: Checkout sources
        uses: actions/checkout@6d193bf28034eafb982f37bd894289fe649468fc # v4.1.7
        with:
          repository: EgorPopelyaev/polkadot-sdk
          ref: master
          token: ${{ steps.generate_write_token.outputs.token }}

      - name: Import gpg keys
        run: |
          . ./.github/scripts/common/lib.sh

          import_gpg_keys

      - name: Config git
        run: |
          git config --global commit.gpgsign true
          git config --global gpg.program /home/runner/.local/bin/pgpkms-git
          git config --global user.name "ParityReleases"
          git config --global user.email "release-team@parity.io"
          git config --global user.signingKey "D8018FBB3F534D866A45998293C5FB5F6A367B51"

      - name: Create or switch to weekly release branch
        run: |
          . ./.github/scripts/common/lib.sh

          checkout_or_switch_branch "$WEEKLY_BRANCH_NAME"
          git show-ref "$WEEKLY_BRANCH_NAME"

      - name: Bump versions, reorder prdocs and push stable branch
        env:
          GH_TOKEN: ${{ steps.generate_write_token.outputs.token }}
        run: |
          . ./.github/scripts/release/release_lib.sh

          if [ "${{ inputs.is_new_weekly }}" = true ]; then
            NODE_VERSION="${{ needs.validate-inputs.outputs.node_version }}"
            NODE_VERSION_PATTERN="\(NODE_VERSION[^=]*= \)\".*\""
            set_version "$NODE_VERSION_PATTERN" $NODE_VERSION "polkadot/node/primitives/src/lib.rs"
            commit_with_message "Bump node version to $NODE_VERSION in polkadot-cli"
            set_version "$NODE_VERSION_PATTERN" $NODE_VERSION "cumulus/polkadot-omni-node/lib/src/nodes/mod.rs"
            commit_with_message "Bump node version to $NODE_VERSION in polkadot-omni-node-lib"

            SPEC_VERSION=$(get_spec_version $NODE_VERSION)
            runtimes_list=$(get_filtered_runtimes_list)
            set_spec_versions $SPEC_VERSION "${runtimes_list[@]}"
          fi

          reorder_prdocs $WEEKLY_BRANCH_NAME

          gh auth setup-git

          git push origin "$WEEKLY_BRANCH_NAME"

      # - name: Tag RC after branch off
      #   env:
      #     GH_TOKEN: ${{ steps.generate_write_token.outputs.token }} # or use a PAT with workflow scope
      #   run: |
      #     stable_tag_base=polkadot-${{ needs.validate-inputs.outputs.weekly_version }}
      #     gh workflow run release-11_rc-automation.yml \
      #       --repo ${{ github.repository }} \
      #       --ref ${{ needs.validate-inputs.outputs.weekly_version }} \
      #       --field version=${stable_tag_base}

  tag-rc:
    needs: [ validate-inputs, create-stable-branch ]
    uses: ./.github/workflows/release-11_rc-automation.yml
    with:
      version: polkadot-${{ needs.validate-inputs.outputs.weekly_version }}
    secrets:
      PGP_KMS_SIGN_COMMITS_KEY:  ${{ secrets.PGP_KMS_SIGN_COMMITS_KEY }}
      PGP_KMS_HASH:  ${{ secrets.PGP_KMS_HASH }}
      AWS_ACCESS_KEY_ID:  ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_DEFAULT_REGION:  ${{ secrets.AWS_DEFAULT_REGION }}
      RELEASE_BACKPORT_AUTOMATION_APP_PRIVATE_KEY: ${{ secrets.RELEASE_BACKPORT_AUTOMATION_APP_PRIVATE_KEY }}
      # RELEASENOTES_MATRIX_V2_ACCESS_TOKEN: ${{ secrets.RELEASENOTES_MATRIX_V2_ACCESS_TOKEN }}
